development:
  host: localhost
  database: godfather_development

test:
  host: localhost
  database: godfather_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
require "rubygems"
require "mongo_mapper"
class Test
  include MongoMapper::Document
  key:TestId,            Integer
  key:ValueString,       String
  key:ValueInteger,      Integer
end